title: "Richard Jerousek"
name: "Richard Jerousek"

url: "https://richardjerousek.com"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
